export const SET_STATE = "SET_STATE"; // trust me, I'm a doctor...
export const TICK_POSITION_UPDATE = "TICK_POSITION_UPDATE";
export const TRACK_SEQUENCE_UPDATE = "TRACK_SEQUENCE_UPDATE";
export const TRACKS_ADD = "TRACKS_ADD";
export const TRACKS_REMOVE = "TRACKS_REMOVE";
export const TRACKS_UPDATE_NAME = "TRACKS_UPDATE_NAME";
export const TRACKS_UPDATE_EDITING = "TRACKS_UPDATE_EDITING";
export const TRACKS_UPDATE_COLLAPSED = "TRACKS_UPDATE_COLLAPSED";